os: applicationsware
text: 'Vanguard ApplicationsWare'
type: network
icon: vanguard
over:
    - { graph: device_bits, text: 'Device Traffic' }
discovery:
    - sysObjectID:
        - .1.3.6.1.4.1.449.2.1.
