sudo: required
language: php
matrix:
  fast_finish: true
  include:
  - php: 7.0
  - php: 5.3
    env: SKIP_STYLE_CHECK=1
  - php: 5.4
    env: SKIP_STYLE_CHECK=1
  - php: 5.5
    env: SKIP_STYLE_CHECK=1
  - php: 5.6
    env: SKIP_STYLE_CHECK=1 EXECUTE_BUILD_DOCS=true
#  - php: hhvm
#    env: SKIP_STYLE_CHECK=1

  allow_failures:
  - php: hhvm

cache:
  directories:
    - vendor
    - $HOME/.cache/pip
    - $HOME/.composer/cache

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y snmp

install:
  - composer install --prefer-dist --no-interaction
  - pip install --user snmpsim
  - pip install --user pylint

before_script:
  - python2 $HOME/.local/bin/snmpsimd.py --data-dir=$TRAVIS_BUILD_DIR/tests/snmpsim --agent-udpv4-endpoint=127.0.0.1:11161 --logging-method=file:/tmp/snmpsimd.log --daemon --pid-file=/tmp/snmpsimd.pid

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $EXECUTE_BUILD_DOCS == "true" && bash scripts/deploy-docs.sh

after_failure:
  - cat /tmp/snmpsimd.log

script:
  - php scripts/pre-commit.php -l
  - php scripts/pre-commit.php -s
  - SNMPSIM=1 phpunit --stop-on-failure
  - bash -n daily.sh
  - pylint -E poller-wrapper.py discovery-wrapper.py poller-service.py
