sudo: required
language: php
services:
  - mysql
matrix:
  fast_finish: true
  include:
  - php: 7.3
    env: SKIP_STYLE_CHECK=1 SKIP_BROWSER_TEST=1
  - php: 7.2
    env: SKIP_UNIT_CHECK=1
  - php: 7.1
    env: SKIP_STYLE_CHECK=1 SKIP_BROWSER_TEST=1 EXECUTE_BUILD_DOCS=true

cache:
  directories:
    - vendor
    - $HOME/.cache/pip
    - $HOME/.composer/cache

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y snmp fping python3-pip
  - mysql -e 'CREATE DATABASE librenms_phpunit_78hunjuybybh CHARACTER SET utf8 COLLATE utf8_unicode_ci;'
  - cp tests/config/config.test.php config.php

install:
  - composer install --prefer-dist --no-interaction
  - pip install --user snmpsim pylint mysql-python

after_failure:
  - tail /tmp/snmpsimd.log

script:
  - set -e
  - export FILES=$(git diff --diff-filter=d --name-only master | tr '\n' ' '|sed 's/,*$//g')
  - php scripts/pre-commit.php -q -l
  - php scripts/pre-commit.php -q -s
  - php scripts/pre-commit.php -u --db --snmpsim --fail-fast
  - test "$SKIP_BROWSER_TEST" -eq 1 || ((php artisan serve 2>/dev/null &) && php artisan dusk:update && php artisan dusk)
  - bash -n daily.sh
  - pylint -E poller-wrapper.py discovery-wrapper.py
  - bash scripts/deploy-docs.sh
  - set +e
