os: linux
language: php
addons:
  chrome: stable
services:
  - mysql
env:
  global:
    APP_ENV=testing
jobs:
  fast_finish: true
  include:
  - php: 7.4
    dist: focal
    env: SKIP_STYLE_CHECK=1 SKIP_WEB_CHECK=1
  - php: 7.3
    dist: bionic
    env: SKIP_UNIT_CHECK=1
  - php: 7.2
    dist: bionic
    env: SKIP_STYLE_CHECK=1 SKIP_WEB_CHECK=1 EXECUTE_BUILD_DOCS=true

cache:
  directories:
    - vendor
    - $HOME/.cache/pip
    - $HOME/.composer/cache

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y snmp fping python3-pip python3-setuptools
  - mysql -e 'CREATE DATABASE librenms_phpunit_78hunjuybybh CHARACTER SET utf8 COLLATE utf8_unicode_ci;'
  - cp .env.travis .env

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - pip3 install --user snmpsim PyMySQL pylint
  - test -n "$SKIP_WEB_CHECK" || php artisan dusk:update --detect

after_failure:
  - tail /tmp/snmpsimd.log
  - cat storage/logs/*.log
  - cat logs/*.log

after_success:
  - scripts/deploy-docs.sh

before_script:
  - phpenv config-rm xdebug.ini
  - test -n "$SKIP_WEB_CHECK" || php artisan serve --env=dusk.testing  2>/dev/null &
  - test -n "$SKIP_UNIT_CHECK" || ~/.local/bin/snmpsimd.py --data-dir=tests/snmpsim --agent-udpv4-endpoint=127.1.6.2:1162 --logging-method=file:/tmp/snmpsimd.log &

script:
  - php artisan dev:check ci
