site_name: LibreNMS Docs
docs_dir: doc
theme:
  name: material
  logo: img/librenms.svg
  language: en
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature: null
site_dir: out
site_url: https://docs.librenms.org
markdown_extensions:
    - pymdownx.tasklist
    - pymdownx.tilde
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.highlight:
        extend_pygments_lang:
          - name: php
            lang: php
            options:
              startinline: true
plugins:
  - macros:
      j2_variable_start_string: '@='
      j2_variable_end_string: '=@'
  - search
  - exclude:
      glob:
        - "General/Changelogs/*"
        - "Dockerfile"
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
    - librenms.css
extra_javascript:
    - librenms-docs.js
extra:
    article_nav_top: false
    article_nav_bottom: true
    php:
        version_min: 7.3
site_author: LibreNMS
site_description: LibreNMS user and developer documentation
repo_url: https://github.com/librenms/librenms/
edit_uri: edit/master/doc
repo_name: GitHub
google_analytics: ['UA-79149977-2', 'docs.librenms.org']
nav:
  - Home: index.md
  - 1. General:
      - Acknowledgements: General/Acknowledgement.md
      - Changelog: General/Changelog.md
      - Code of Conduct: General/CODE_OF_CONDUCT.md
      - Features: Support/Features.md
      - Welcome to Observium users: General/Welcome-to-Observium-users.md
  - 2. Installing:
      - How to install LibreNMS: Installation/index.md
      - Install LibreNMS: Installation/Install-LibreNMS.md
      - LibreNMS VMs: Installation/Images.md
      - Migrating from Observium: Installation/Migrating-from-Observium.md
  - 3. Getting started:
      - Choosing a release: General/Releases.md
      - Adding a device: Support/Adding-a-Device.md
      - Grouping Devices: Extensions/Device-Groups.md
      - Submitting stats: General/Callback-Stats-and-Privacy.md
      - Updating an install: General/Updating.md
  - 4. Basic Setup:
      - Applications: Extensions/Applications.md
      - Check_MK Setup: Extensions/Agent-Setup.md
      - Billing Module: Extensions/Billing-Module.md
      - Dell OpenManage: Extensions/Dell-OpenManage.md
      - World Map: Extensions/World-Map.md
      - Interface Description Parsing: Extensions/Interface-Description-Parsing.md
      - Network Map: Extensions/Network-Map.md
      - Syslog: Extensions/Syslog.md
      - Dashboards: Extensions/Dashboards.md
      - Supermicro: Extensions/Supermicro.md
  - 5. Advanced Setup:
      - 1 Minute Polling: Support/1-Minute-Polling.md
      - Fast Ping Checking: Extensions/Fast-Ping-Check.md
      - Environment Variables: Support/Environment-Variables.md
      - Configuration Docs: Support/Configuration.md
      - Authentication Options: Extensions/Authentication.md
      - Two-Factor Auth: Extensions/Two-Factor-Auth.md
      - Auto-discovery Setup: Extensions/Auto-Discovery.md
      - Scaling LibreNMS: Extensions/Distributed-Poller.md
      - RRDCached: Extensions/RRDCached.md
      - Sub-directory Support: Extensions/Sub-Directory.md
      - Varnish: Extensions/Varnish.md
      - Dispatcher Service (RC): Extensions/Dispatcher-Service.md
      - RRDTune: Extensions/RRDTune.md
      - IRC Bot: Extensions/IRC-Bot.md
      - IRC Bot Extensions: Extensions/IRC-Bot-Extensions.md
      - SNMP Proxy: Extensions/SNMP-Proxy.md
      - SNMP Trap Handler: Extensions/SNMP-Trap-Handler.md
      - Customizing the Web UI: Extensions/Customizing-the-Web-UI.md
      - Bare Dashboard: Support/Bare-Dashboard.md
      - Cleanup Options: Support/Cleanup-options.md
  - 6. 3rd Party Integration:
      - Gateone: Extensions/Gateone.md
      - Graylog: Extensions/Graylog.md
      - Nagios Plugins: Extensions/Services.md
      - NFSen: Extensions/NFSen.md
      - Oxidized: Extensions/Oxidized.md
      - Rancid: Extensions/Rancid.md
      - PeeringDB: Extensions/PeeringDB.md
      - Proxmox: Extensions/Proxmox.md
      - Storing Metrics:
          - Intro: Extensions/Metric-Storage.md
          - Graphite: Extensions/metrics/Graphite.md
          - InfluxDB: Extensions/metrics/InfluxDB.md
          - OpenTSDB: Extensions/metrics/OpenTSDB.md
          - Prometheus: Extensions/metrics/Prometheus.md
      - Smokeping: Extensions/Smokeping.md
      - Weathermap: Extensions/Weathermap.md
  - 7. API:
      - Using the API: API/index.md
      - Devices: API/Devices.md
      - DeviceGroups: API/DeviceGroups.md
      - Ports: API/Ports.md
      - PortGroups: API/PortGroups.md
      - Port_Groups: API/Port_Groups.md
      - Alerts: API/Alerts.md
      - Routing: API/Routing.md
      - Switching: API/Switching.md
      - Inventory: API/Inventory.md
      - Bills: API/Bills.md
      - ARP: API/ARP.md
      - Services: API/Services.md
      - System: API/System.md
      - Logs: API/Logs.md
      - Locations: API/Locations.md
  - 8. Alerting:
      - Intro: Alerting/index.md
      - Introduction: Alerting/Introduction.md
      - Rules: Alerting/Rules.md
      - Templates: Alerting/Templates.md
      - Transports: Alerting/Transports.md
      - Creating Transports: Alerting/Creating-Transport.md
      - Entities: Alerting/Entities.md
      - Macros: Alerting/Macros.md
      - Testing: Alerting/Testing.md
      - Device Dependencies: Alerting/Device-Dependencies.md
  - 9. Getting help:
      - How to get help: Support/index.md
      - FAQ: Support/FAQ.md
      - Install Validation: Support/Install Validation.md
      - Performance: Support/Performance.md
      - Discovery Support: Support/Discovery Support.md
      - Poller Support: Support/Poller Support.md
      - Example Hardware Setups: Support/Example-Hardware-Setup.md
      - Remote Monitoring VPN: Support/Remote-Monitoring-VPN.md
      - SNMP Configuration Examples: Support/SNMP-Configuration-Examples.md
      - SSL Configuration: Support/SSL-Configuration.md
      - Device Troubleshooting: Support/Device-Troubleshooting.md
      - Device Sensors: Support/Device-Sensors.md
  - 10. Contributing + Developing:
      - Contributing: Developing/index.md
      - Getting Started: Developing/Getting-Started.md
      - Using Git: Developing/Using-Git.md
      - Code Guidelines: Developing/Code-Guidelines.md
      - Style Guidelines: Developing/Style-Guidelines.md
      - Validating Code: Developing/Validating-Code.md
      - Code Structure: Developing/Code-Structure.md
      - Creating Documentation: Developing/Creating-Documentation.md
      - Licensing: Developing/Licensing.md
      - Component: Extensions/Component.md
      - Support for a new OS:
          - Intro: Developing/Support-New-OS.md
          - Initial Detection: Developing/os/Initial-Detection.md
          - Mem/CPU Information: Developing/os/Mem-CPU-Information.md
          - Test Units: Developing/os/Test-Units.md
          - Health Information: Developing/os/Health-Information.md
          - Wireless Sensors: Developing/os/Wireless-Sensors.md
          - Custom Graphs: Developing/os/Custom-Graphs.md
          - Settings: Developing/os/Settings.md
          - Sensor State Support: Developing/Sensor-State-Support.md
      - SNMP Traps: Developing/SNMP-Traps.md
      - Dynamic Config: Developing/Dynamic-Config.md
      - Merging Pull Requests: Developing/Merging-Pull-Requests.md
      - Creating Release: Developing/Creating-Release.md
      - Plugin System: Extensions/Plugin-System.md
  - 11. Misc:
      - Security information: General/Security.md
      - CLI Scripts: Support/CLI-Tools.md
      - Device Notes:
          - Intro: Support/Device-Notes/index.md
          - Carel pCOweb: Support/Device-Notes/Carel-pCOweb-Devices.md
          - Asuswrt-Merlin: Support/Device-Notes/AsuswrtMerlin.md
          - OpenWRT: Support/Device-Notes/Openwrt.md
