name: doc

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/doc.yml'
      - 'doc/**'
      - 'mkdocs.yml'
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/doc.yml'
      - 'doc/**'
      - 'mkdocs.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build mkdocs Docker image
        run: |
          docker build -t mkdocs -f ./doc/Dockerfile ./
      -
        name: Build docs
        run: |
          docker run --rm -v "$(pwd):/docs" mkdocs build --strict
          sudo chown -R $(id -u):$(id -g) ./out
      -
        name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v2
        with:
          pages_threshold: major_outage
      -
        name: Deploy
        if: github.event_name != 'pull_request' && endsWith(github.ref, github.event.repository.default_branch)
        uses: crazy-max/ghaction-github-pages@v2
        with:
          repo: librenms/docs.librenms.org
          target_branch: main
          keep_history: true
          build_dir: out
        env:
          GH_PAT: ${{ secrets.DOCS_TOKEN }}
